### ISSUE TITLE
Move repo to cyclejs-community org

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/cycle-canvas#14]
I feel a bit guilty about having this under my username when really the hard work is being done by you awesome contributors.

Is it okay if I move this repo into the new cyclejs-community org? https://github.com/cyclejs-community

I think that would better reflect who the true authors are.

@apretto @schempy @edwin-nz

**Comment by schempy** [comment]
That's great! Fine with me.

**Comment by apretto** [comment]
Sure, let's do it.
