### ISSUE TITLE
Add support for polygons

### ISSUE THREAD

**Issue by apretto** [cyclejs-community/cycle-canvas#15]
I propose to add the `polygon` function to the driver:
- given a list of points, draw a closed polygon (either filled, stroked or both). See https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes#Drawing_a_triangle

I'll start an implementation for it, but any input is welcome.

The signature I'm considering will look something like this:

``` javascript
polygon({
  transformations: [],
  points: [{x: 10, y: 10}, {x: 20, y: 10}, {x: 15, y: 17}],
  draw: [
    {fill: 'purple'}
  ]
}); // draw a purple triangle
```

Also, perhaps we should consider removing the `x` and `y` parameter from the `line` function, and have that point being the first one in the list of `points`, just like I propose here in the polygon.

Thoughts on this last idea?

**Comment by Widdershin** [comment]
I like the proposed API 👍 

I can see the use of having `x` and `y` on line/polygon so that you can offset all the points (although I suppose that can be achieved with a translation). I'm indifferent to removal.
