### ISSUE TITLE
Publishing new versions to NPM

### ISSUE THREAD

**Issue by grozen** [cyclejs-community/cycle-canvas#22]
How does one go about publishing new versions of this package to NPM? Only @schempy appears to have the appropriate credentials.

**Comment by Widdershin** [comment]
@schempy any chance we can add a few people as publishers.

I think you just need to run:

`npm run owner add grozen cycle-collection`

Assuming that @grozen has an npm account with that user name. (Can you confirm?)

**Comment by grozen** [comment]
Confirmed, @Widdershin.

**Comment by Widdershin** [comment]
Cool.

I made a mistake in the above command, it should read:

`npm owner add grozen cycle-collection`

**Comment by schempy** [comment]
I added @grozen to cycle-canvas on npm. Let me know if there are any problems

**Comment by grozen** [comment]
Works terrifically. It's a shame there doesn't seem a way to add a group to make this whole sort of thing more robust.
