### ISSUE TITLE
makeCanvasDriver does not work without its second argument

### ISSUE THREAD

**Issue by grozen** [cyclejs-community/cycle-canvas#24]
While this is not clearly documented in any way (which is a thing that should also be fixed, possibly while fixing this), it seems very sensible that `makeCanvasDriver`'s second argument should be optional, assuming you supply its first argument.

The reasoning behind this is that the first argument causes the driver to attach to an existing canvas, which already has its own width and height, making specifying them redundant if not counterproductive.

What happens presently is that the builder method throws a type error as it assumes the second argument has a value and tries to access its properties.

**Comment by Widdershin** [comment]
Reasonable. It would also perhaps be nice to have an easy way to get a fullscreen canvas.

**Comment by grozen** [comment]
Fixed with #26.
