### ISSUE TITLE
Feelings about eslint?

### ISSUE THREAD

**Issue by grozen** [cyclejs-community/cycle-canvas#29]
Finally getting back on the bandwagon here, I was all rearing to write some code. However, I realized that while in most of my recent endeavors I've been using ESLint for hints and consistency, this is not the sort of thing I feel comfortable subjecting the project to without consulting others.

So, how do we feel about ESLint? Would it be all right to incorporate it as a development dependency?

**Comment by Widdershin** [comment]
Fully in favour of this.

**Comment by grozen** [comment]
Linting has been added in #30.
