### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/cycle-canvas#6]
Before we release v0.1 it would be great to add some documentation to the README around the various options that are currently available.

@schempy @apretto do either of you feel like taking a crack at this? I probably won't get to it this week (currently traveling, will only be home for a day before I have more traveling to do). I'm more than happy to help though.

I think this is the last thing we need to do before our first release.

**Comment by schempy** [comment]
@Widdershin I'll take a crack at it!

**Comment by Widdershin** [comment]
Awesome :)

**Comment by schempy** [comment]
@Widdershin I added API documentation. Feel free to make changes and additions :)

**Comment by Widdershin** [comment]
That is fantastic. Very detailed and thorough, you should be proud. How would you like to release the first version? I can help you get it published to npm

**Comment by schempy** [comment]
Thanks! That would be awesome if I could release the first version. Any help would be great!

**Comment by Widdershin** [comment]
@schempy I've opened #7 with a big checklist of stuff to do for the initial release! Hope that helps and everything is clear. Let me know if you run into any problems 😄
