### ISSUE TITLE
Decide how to proceed with transformations

### ISSUE THREAD

**Issue by apretto** [cyclejs-community/cycle-canvas#9]
I added this as a comment on @schempy's PR last week, but it was after it was closed and I think people missed it (https://github.com/Widdershin/cycle-canvas/pull/4#issuecomment-216465077).

Here it is again:

I ran into a problem when trying to update the flappy bird example app to use translate and rotate. The problem is that the way these transformations are performed in a canvas is reminiscent of how these things have been done in computer graphics since the 90s (I would guess). That means there's a hidden state in the canvas with all the transformations done so far. You can see it in the example for rotate in MDN: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Transformations#A_rotate_example

There you'll see that, to rotate the square around the center where it's going to be drawn, you have to:
- translate to the middle of where you'll draw the square (offsets + half the width/height)
- rotate the angle you want
- translate back (just `-1 *` the numbers of the first step)
- draw the square

I dislike this as it creates a cognitive overhead where you have to mentally do the transformations in your head to figure out if they are correct (specially when they are not, as there's a good chance the thing you wanted to draw is going to be off screen and it's harder to figure out which step is the problem).

Some options to approach this problem that I can think of:
1. just expose what the canvas api implements, and let the user of the driver deal with transformations and states;
2. expose the 'low level' api for now, and build abstractions on top of it (for example a `rotateAround` that does that rotate around a specified coordiante)
3. come up with a way to delay applying the transformations, and then process them all in one go so they 'do the right thing'
4. read up and see if anyone figure out a way to do these type of transformations in a functional way.

How it could like for `1`:

``` javascript
group([
  saveState(),
  translate({x: 55, y: 55}),
  rotate({angle: 0.5}),
  translate({x: -55, y: -55}),
  rect({x: 50, y: 50, width: 10, height: 10, draw: [{fill: 'black'}]),
  restoreState()
])
```

How it could like for `2`:

``` javascript
rotateAround(
  {x: 55, y: 55, angle: 0.5},
  [
    rect({x: 50, y: 50, width: 10, height: 10, draw: [{fill: 'black'}])
  ]
)
```

I'm not sure how it could look like for `3` or `4`. One thing that I believe is that these approaches are harder to do having the transformations being attributes to regular draw elements (they would have to be a list to allow the process demonstrated here).

Thoughts?

**Comment by Widdershin** [comment]
What about a variation on `1` that looks like this (perhaps this is what you were imagining with `3`):

``` js
rect({
  x: 50,
  y: 50,
  width: 10,
  height: 10,
  draw: [{fill: 'black'}]),
  transform: [
    translate({x: 55, y: 55}),
    rotate({angle: 0.5}),
    translate({x: -55, y: -55}),
  ]
])
```

With saveState and restoreState being automatically called.

Do you think think this approach would work?

**Comment by apretto** [comment]
That can work.

Another thing that's tangentially related: the current implementation only applies transformations to the element itself, any children that it has won't be affected by that transformation. I can see the case for having the behavior be that, but I would first assume that the children would be drawn in the "context" (read: all transformations made) as their parent.

**Comment by apretto** [comment]
Closing this.
